# Stage 1: Build stage
FROM python:3.12-slim AS builder

WORKDIR /app

# Install minimal OS deps and uv
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates git build-essential aria2 \
 && curl -LsSf https://astral.sh/uv/install.sh | sh \
 && cp ~/.local/bin/uv /usr/local/bin/uv \
 && chmod +x /usr/local/bin/uv

# Copy app files and install deps
COPY README.md src/* pyproject.toml uv.lock ./
RUN uv sync

# Stage 2: Runtime stage
FROM python:3.12-slim

WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates aria2 nala \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Copy only necessary files from the builder stage
COPY --from=builder /app /app
COPY --from=builder /usr/local/bin/uv /usr/local/bin/uv

CMD ["uv", "run", "handler.py"]
