name: Docker Images [Dev]

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: runpod/tetra-rp

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup dependencies
        run: |
          uv sync
          git submodule update --remote --merge
          cp tetra-rp/src/tetra_rp/protos/remote_execution.py .

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-cpu
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cpu:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        id: run-tests
        uses: runpod/runpod-test-runner@v2.1.0
        with:
          image-tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          runpod-api-key: ${{ secrets.RUNPOD_API_KEY }}
          request-timeout: 600
